# Generated by Django 5.2.7 on 2025-10-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('external_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
