USER_NOT_FOUND="User not exist in BD"
USER_NOT_FOUND_API="User not exist in API"
ERROR_CONNECTION_TO_EXTERNAL_API="Error connecting to an external service."
EMAIL_ERROR="Dont sent email"
EMAIL_MESSAGE="Your state is inactive"
EMAIL_SUBJECT="Alert"